### ISSUE TITLE
Odd serif before comining macron

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen#28]
See "Bey vollko..." at http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=358&view=facsimile_document

**Comment by thvitt** [comment]
This is only visible in Chrome/Chromium, and there is no code that provokes this, so it's probably a rendering bug related to the m̄. Maybe its the best solution also for the different rendering to just implement a glyph for that character in our fonts

**Comment by thvitt** [comment]
I think I see the problem:

The Ubuntu font family doesn't have a glyph for U+0304 COMBINING MACRON (it has a plain spacing macron, though). So I guess Chrome takes the combining glyph from a different font, and mis-renders the stuff up to the combining character in this way as well. Other browsers simply take the combining glyph from a different font, and they don't get the metrics right. 

A possible solution might be to modify the Ubuntu fonts in order to make them contain the missing glyph. The glyph itself could just be copied from U+00AF MACRON, however, the metrics/kerning would need to be adjusted.

Now we only need someone who knows enough about fonts to do that properly …
